apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  {{- with .Values.metadata }}
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}

spec:
  {{- toYaml .Values.spec | nindent 2 }}