apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Ofirfr/LocalKube.git
        revision: HEAD
        directories:
          - path: monitoring
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Ofirfr/LocalKube.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
