apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-grafana-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Ofirfr/LocalKube.git"
      targetRevision: HEAD
      ref: local-kube-repo
    - repoURL: "https://github.com/cloudnative-pg/cloudnative-pg.git"
      targetRevision: HEAD
      ref: cnpg-repo
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.2.0
      helm:
        parameters:
          - name: service.type
            value: NodePort
          - name: service.nodePort
            value: "30009"
          - name: service.port
            value: "80"
          - name: service.targetPort
            value: "3000"
        releaseName: prometheus-grafana-stack
        valueFiles:
          - $cnpg-repo/docs/src/samples/monitoring/kube-stack-config.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
      - PruneLast=true
