apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: first-demo-cnpg-clusters-application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/Ofirfr/LocalKube.git"
        revision: HEAD
        files:
          - path: first-demo/postgres/cnpg-clusters/**/config.json
  template:
    metadata:
      name: "{{ .dba.metadata.name }}"
    spec:
      project: default
      source:
        repoURL: "https://ofirfr.github.io/LocalKube"
        targetRevision: 0.1.1
        chart: cnpg-cluster
        helm:
          parameters:
            - name: cluster.instances
              value: "{{ .app.replicas }}"
          releaseName: "{{ .dba.metadata.name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .dba.metadata.namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
