apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: first-postgres-cluster-app-one
  namespace: argocd
spec:
  instances: 3
  storage:
    size: 500Mi
  resources:
    requests:
      cpu: "200m"
      memory: "200Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"
