apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Ofirfr/LocalKube.git"
    targetRevision: HEAD
    path: first-demo/applicationset.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
