spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 1
  bootstrap:
    initdb:
      import:
        type: microservice
        schemaOnly: true
        databases:
          - ofirdb
        source:
          externalCluster: best-app-pdb-14
  externalClusters:
  - name: best-app-pdb-14
    connectionParameters:
      host: best-app-pdb-14-rw
      user: postgres
      dbname: postgres
    password:
      name: best-app-pdb-14-superuser
      key: password
