cluster:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  instances: 1
  bootstrap:
    initdb:
      import:
        type: microservice
        schemaOnly: true
        databases:
          - ofirdb
        source:
          externalCluster: best-app-pdb-14
  externalClusters:
  - name: best-app-pdb-14
    connectionParameters:
      host: best-app-pdb-14-cnpg-cluster-rw
      user: postgres
      dbname: ofirdb
    password:
      name: best-app-pdb-14-cnpg-cluster-superuser
      key: password
