apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: first-demo-cnpg-clusters-application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/Ofirfr/LocalKube.git"
        revision: HEAD
        files:
          - path: first-demo/cnpg-clusters/**/config.json
  template:
    metadata:
      name: "{{ .dba.metadata.name }}"
    spec:
      project: default
      source:
        repoURL: "https://cloudnative-pg.github.io/charts"
        targetRevision: "{{ .dba.helm.revision }}"
        chart: cluster
        helm:
          # Parameters from the specific values file will override
          valueFiles:
            - values.yml
            - "{{ .path.path }}/cluster-specific-values.yml"
          # This will always override anything in valuesFiles
          parameters:
            - name: cluster.name
              value: "{{ .dba.metadata.name }}"
            - name: cluster.namespace
              value: "{{ .dba.metadata.namespace }}"
          releaseName: "{{ .dba.metadata.name }}-cnpg-cluster"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .dba.metadata.namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
