apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: first-demo-cnpg-clusters-application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/Ofirfr/LocalKube.git"
        revision: HEAD
        files:
        # Change it to your path
          - path: first-demo/cnpg-clusters/**/config.json
  template:
    metadata:
      name: "{{ .dba.metadata.name }}"
    spec:
      project: default
      sources:
      # This is needed for Argo to read the specific-values file
        - repoURL: "https://github.com/Ofirfr/LocalKube.git"
          targetRevision: HEAD
          ref: git-repo
      # This might (and probably will) be a different repo
        - repoURL: "https://ofirfr.github.io/LocalKube/"
          targetRevision: "{{ .dba.helm.revision }}"
          chart: cnpg-cluster
          helm:
            # Parameters from the specific values file will override
            valueFiles:
              - "$git-repo/first-demo/app-set/default-cnpg-values.yml"
              - "$git-repo/{{ .path.path }}/cluster-specific-values.yml"
            # These will always override anything in valuesFiles
            parameters:
              - name: metadata.name
                value: "{{ .dba.metadata.name }}"
              - name: metadata.namespace
                value: "dba-cnpg"
            releaseName: "{{ .dba.metadata.name }}-cnpg-cluster"
      destination:
        server: https://kubernetes.default.svc
        namespace: "dba-cnpg"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      # You may want to add more sync options
        syncOptions:
          - CreateNamespace=true
