apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workflows
spec:
  generators:
    - git:
        repoURL: "https://github.com/Ofirfr/LocalKube.git"
        revision: HEAD
        directories:
          - path: 'first-demo/workflows/**/**'
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: "https://github.com/Ofirfr/LocalKube.git"
        targetRevision: 'main'
        path: '{{path}}'
        directory:
          recurse: true 
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
