apiVersion: v1
kind: Secret
metadata:
  name: minio-access-keys
  namespace: dba-cnpg
type: Opaque
stringData:
  ACCESS_KEY_ID: vbjUcybJG6wCclcqXE1A # base64 encoded 'myUsername'
  ACCESS_SECRET_KEY: nmLDW12tenGNIyncmYtzzfujsftqJim9yJjt5aqi # base64 encoded 'myPassword'
