apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-node3
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - kind-worker3
