apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-service-account
  namespace: best-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: best-app  # The namespace where the Role applies
  name: all-access-role
rules:
  - apiGroups: ["*"]      # Allows access to all API groups
    resources: ["*"]      # Allows access to all resources
    verbs: ["*"]          # Allows all actions (get, list, watch, create, update, delete, etc.)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-rolebinding
  namespace: best-app
subjects:
  - kind: ServiceAccount
    name: argo-service-account
    namespace: best-app
roleRef:
  kind: Role
  name: all-access-role
  apiGroup: rbac.authorization.k8s.io
