# permissions for end users to edit nodelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operators
    app.kubernetes.io/managed-by: kustomize
  name: nodelabel-editor-role
rules:
- apiGroups:
  - label.ofir.king
  resources:
  - nodelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - label.ofir.king
  resources:
  - nodelabels/status
  verbs:
  - get
