apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster-1
  namespace: first-demo
spec:
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    size: 500Mi
  resources:
    requests:
      cpu: "200m"
      memory: "200Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"
